# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdc4c4c14389ad48c3c5af03258c182172fecca0d7f26c2d82ad7d88eefb9b581abe4e761e1c09c70e8ad01a3784f93876fb38eba5b1eb766c3a9d0b17e6dbba

test:
  secret_key_base: c6b6f19b8b720db68d1b29229c1e36701eabb883cadbd7b8897cbd6af22fa822a1832f305d6bb84bdac1aeb7379144d287374474b69ad13faddfebbf3d3ecb28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
